[2025-05-19T22:46:43.794+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_analysis.ingest_data manual__2025-05-19T22:46:40.625485+00:00 [queued]>
[2025-05-19T22:46:43.802+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_analysis.ingest_data manual__2025-05-19T22:46:40.625485+00:00 [queued]>
[2025-05-19T22:46:43.803+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-19T22:46:43.816+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ingest_data> on 2025-05-19 22:46:40.625485+00:00
[2025-05-19T22:46:43.820+0000] {standard_task_runner.py:60} INFO - Started process 141 to run task
[2025-05-19T22:46:43.823+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_price_analysis', 'ingest_data', 'manual__2025-05-19T22:46:40.625485+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmpnwu6pj0i']
[2025-05-19T22:46:43.824+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask ingest_data
[2025-05-19T22:46:43.880+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_price_analysis.ingest_data manual__2025-05-19T22:46:40.625485+00:00 [running]> on host 7753327d0419
[2025-05-19T22:46:43.949+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_analysis' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T22:46:40.625485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T22:46:40.625485+00:00'
[2025-05-19T22:46:43.965+0000] {data_ingestion.py:16} INFO - CSV validation successful for: /opt/***/dags/data/Flight_Price_Dataset_of_Bangladesh.csv
[2025-05-19T22:46:43.966+0000] {data_ingestion.py:17} INFO - Columns found: Airline, Source, Source Name, Destination, Destination Name, Departure Date & Time, Arrival Date & Time, Duration (hrs), Stopovers, Aircraft Type, Class, Booking Source, Base Fare (BDT), Tax & Surcharge (BDT), Total Fare (BDT), Seasonality, Days Before Departure
[2025-05-19T22:46:43.967+0000] {data_ingestion.py:37} INFO - Reading CSV file: /opt/***/dags/data/Flight_Price_Dataset_of_Bangladesh.csv
[2025-05-19T22:46:44.261+0000] {data_ingestion.py:53} INFO - CSV loaded with 57000 rows and 17 columns
[2025-05-19T22:46:44.262+0000] {data_ingestion.py:54} INFO - Columns after cleaning: Airline, Source, Source_Name, Destination, Destination_Name, Departure_Date_Time, Arrival_Date_Time, Duration_hrs, Stopovers, Aircraft_Type, Class, Booking_Source, Base_Fare_BDT, Tax_Surcharge_BDT, Total_Fare_BDT, Seasonality, Days_Before_Departure
[2025-05-19T22:46:45.067+0000] {data_ingestion.py:67} INFO - Inserting data into MySQL table: flight_data
[2025-05-19T22:46:45.075+0000] {data_ingestion.py:99} ERROR - Error in csv_to_mysql: The conn_id `mysql_conn` isn't defined
[2025-05-19T22:46:45.083+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/data_ingestion.py", line 69, in csv_to_mysql
    conn = mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 187, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_conn` isn't defined
[2025-05-19T22:46:45.091+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_price_analysis, task_id=ingest_data, execution_date=20250519T224640, start_date=20250519T224643, end_date=20250519T224645
[2025-05-19T22:46:45.105+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task ingest_data (The conn_id `mysql_conn` isn't defined; 141)
[2025-05-19T22:46:45.120+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-19T22:46:45.142+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
